# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: hyan36/biggreenbutton
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest 
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $(token)" "https://api.digitalocean.com/v2/apps/$(app_id)/deployments"

